import { ClipboardList, Search } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { api } from "../lib/api";
import type { AdminUser, AuditLog } from "../types";

const actionLabels: Record<string, string> = { LOGIN: "Login", LOGIN_FAILED: "Tentativa de login inválida", LOGIN_BLOCKED: "Login bloqueado", LOGOUT: "Logout", PASSWORD_CHANGED: "Senha alterada", PASSWORD_RESET: "Senha recuperada", PASSWORD_CHANGED_BY_ADMIN: "Senha alterada pelo administrador", USER_CREATED: "Usuário criado", USER_UPDATED: "Usuário atualizado", USER_DELETED: "Usuário excluído", RECOVERY_CODE_CREATED: "Código de recuperação emitido", SESSION_REVOKED: "Sessão encerrada" };
export function AuditLogsView() {
  const [items, setItems] = useState<AuditLog[]>([]), [actions, setActions] = useState<string[]>([]), [users, setUsers] = useState<AdminUser[]>([]);
  const [action, setAction] = useState(""), [actor, setActor] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState("");
  const [page, setPage] = useState(1), [pages, setPages] = useState(1), [error, setError] = useState("");
  const load = useCallback(async () => { try { const params = new URLSearchParams({ page: String(page) }); if (action) params.set("action", action); if (actor) params.set("actorUserId", actor); if (from) params.set("from", `${from}T00:00:00.000Z`); if (to) params.set("to", `${to}T23:59:59.999Z`); const [logs, userData] = await Promise.all([api<{ items: AuditLog[]; actions: string[]; pagination: { pages: number } }>(`/admin/audit-logs?${params}`), users.length ? Promise.resolve(users) : api<AdminUser[]>("/admin/users")]); setItems(logs.items); setActions(logs.actions); setPages(logs.pagination.pages); setUsers(userData); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar a auditoria"); } }, [action, actor, from, to, page, users]);
  useEffect(() => { void load(); }, [load]);
  return <section className="content-section audit-section"><div className="section-heading"><div><p className="eyebrow">Rastreabilidade</p><h1>Auditoria</h1><p className="muted">Consulte acessos e alterações sensíveis realizadas no sistema.</p></div><ClipboardList /></div><div className="audit-filters"><label>Ação<select value={action} onChange={(event) => { setAction(event.target.value); setPage(1); }}><option value="">Todas</option>{actions.map((item) => <option key={item} value={item}>{actionLabels[item] ?? item}</option>)}</select></label><label>Responsável<select value={actor} onChange={(event) => { setActor(event.target.value); setPage(1); }}><option value="">Todos</option>{users.map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select></label><label>De<input type="date" value={from} onChange={(event) => { setFrom(event.target.value); setPage(1); }} /></label><label>Até<input type="date" value={to} onChange={(event) => { setTo(event.target.value); setPage(1); }} /></label><button className="secondary-button compact" onClick={() => void load()}><Search size={15} /> Consultar</button></div>{error && <div className="form-error spaced">{error}</div>}<div className="audit-list">{items.map((item) => <article key={item.id}><span className="audit-dot" /><div><strong>{actionLabels[item.action] ?? item.action}</strong><p>{item.description}</p><small>{item.actor ? `${item.actor.name} · ${item.actor.email}` : "Ação sem usuário autenticado"}{item.ipAddress ? ` · IP ${item.ipAddress}` : ""}</small></div><time>{new Date(item.createdAt).toLocaleString("pt-BR")}</time></article>)}{!items.length && <div className="empty-state"><ClipboardList /><h3>Nenhum registro encontrado</h3></div>}</div>{pages > 1 && <div className="pagination"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><span>{page} de {pages}</span><button disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Próxima</button></div>}</section>;
}
