import { ArrowRight, CheckCircle2, Clock3, Pencil, Plus, Trash2, XCircle } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api } from "../lib/api";
import type { Account, Transfer, TransferStatus } from "../types";

interface Props { accounts: Account[]; onChanged: () => void; }
const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const currentMonth = new Date().toISOString().slice(0, 7);
const today = new Date().toISOString().slice(0, 10);
const statusLabels: Record<TransferStatus, string> = { PENDING: "Agendada", COMPLETED: "Concluída", CANCELED: "Cancelada" };

function monthRange(month: string) { const [year, number] = month.split("-").map(Number); const last = new Date(Date.UTC(year!, number!, 0)).getUTCDate(); return { from: `${month}-01T00:00:00.000Z`, to: `${month}-${String(last).padStart(2, "0")}T23:59:59.999Z` }; }

export function TransfersView({ accounts, onChanged }: Props) {
  const [items, setItems] = useState<Transfer[]>([]), [month, setMonth] = useState(currentMonth), [status, setStatus] = useState<"" | TransferStatus>("");
  const [editing, setEditing] = useState<"new" | Transfer | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const range = monthRange(month), params = new URLSearchParams(range); if (status) params.set("status", status); setItems(await api<Transfer[]>(`/transfers?${params}`)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível carregar as transferências"); } }, [month, status]);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget).entries());
    try { await api(editing === "new" ? "/transfers" : `/transfers/${editing!.id}`, { method: editing === "new" ? "POST" : "PUT", body: JSON.stringify({ ...data, amount: Number(data.amount), date: `${data.date}T00:00:00.000Z`, notes: data.notes || null }) }); setEditing(null); setNotice("Transferência salva com sucesso."); await load(); onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível salvar a transferência"); }
  }
  async function changeStatus(item: Transfer, nextStatus: TransferStatus) {
    try { await api(`/transfers/${item.id}`, { method: "PUT", body: JSON.stringify({ description: item.description, amount: Number(item.amount), date: item.date, status: nextStatus, fromAccountId: item.fromAccountId, toAccountId: item.toAccountId, notes: item.notes }) }); await load(); onChanged(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível atualizar a transferência"); }
  }
  async function remove(item: Transfer) { if (!confirm(`Excluir a transferência “${item.description}”?`)) return; try { await api(`/transfers/${item.id}`, { method: "DELETE" }); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível excluir a transferência"); } }
  const completedTotal = items.filter((item) => item.status === "COMPLETED").reduce((sum, item) => sum + Number(item.amount), 0);
  const pendingTotal = items.filter((item) => item.status === "PENDING").reduce((sum, item) => sum + Number(item.amount), 0);
  return <section className="content-section transfers-section"><div className="section-heading"><div><p className="eyebrow">Movimentação interna</p><h1>Transferências</h1><p className="muted">Mova valores entre suas contas sem alterar receitas ou despesas.</p></div><button className="primary-button compact" disabled={accounts.filter((account) => account.isActive).length < 2} onClick={() => setEditing("new")}><Plus size={18} /> Nova transferência</button></div>
    <div className="transfer-toolbar"><label>Período<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as "" | TransferStatus)}><option value="">Todos</option><option value="COMPLETED">Concluídas</option><option value="PENDING">Agendadas</option><option value="CANCELED">Canceladas</option></select></label><div><small>Movimentado</small><strong>{currency.format(completedTotal)}</strong></div><div><small>Agendado</small><strong>{currency.format(pendingTotal)}</strong></div></div>
    {accounts.filter((account) => account.isActive).length < 2 && <div className="form-error spaced">Cadastre pelo menos duas contas ativas para realizar transferências.</div>}{notice && <div className="admin-notice">{notice}</div>}{error && <div className="form-error spaced">{error}</div>}
    <div className="transfer-list">{items.map((item) => <article key={item.id}><span className="transfer-route"><i style={{ background: item.fromAccount.color }}>{item.fromAccount.name.slice(0, 1)}</i><ArrowRight /><i style={{ background: item.toAccount.color }}>{item.toAccount.name.slice(0, 1)}</i></span><div><strong>{item.description}</strong><span>{item.fromAccount.name} <ArrowRight size={13} /> {item.toAccount.name}</span><small>{new Date(item.date).toLocaleDateString("pt-BR", { timeZone: "UTC" })}{item.notes ? ` · ${item.notes}` : ""}</small></div><strong className="transfer-amount">{currency.format(Number(item.amount))}</strong><span className={`transfer-status ${item.status.toLowerCase()}`}>{item.status === "COMPLETED" ? <CheckCircle2 /> : item.status === "PENDING" ? <Clock3 /> : <XCircle />}{statusLabels[item.status]}</span><span className="row-actions">{item.status === "PENDING" && <button className="icon-button success" onClick={() => void changeStatus(item, "COMPLETED")} title="Concluir"><CheckCircle2 size={16} /></button>}{item.status !== "CANCELED" && <button className="icon-button" onClick={() => void changeStatus(item, "CANCELED")} title="Cancelar"><XCircle size={16} /></button>}<button className="icon-button" onClick={() => setEditing(item)} title="Editar"><Pencil size={16} /></button><button className="icon-button danger" onClick={() => void remove(item)} title="Excluir"><Trash2 size={16} /></button></span></article>)}</div>
    {!items.length && <div className="empty-state"><ArrowRight /><h3>Nenhuma transferência no período</h3><p>Transferências entre contas aparecerão aqui.</p></div>}
    {editing && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setEditing(null)}><section className="modal-card transfer-modal"><div className="modal-header"><div><p className="eyebrow">Transferência interna</p><h2>{editing === "new" ? "Nova transferência" : "Editar transferência"}</h2></div><button className="icon-button" onClick={() => setEditing(null)}><XCircle /></button></div><form onSubmit={submit}><label>Descrição<input name="description" defaultValue={editing === "new" ? "Transferência entre contas" : editing.description} required minLength={2} /></label><div className="form-grid"><label>Conta de origem<select name="fromAccountId" defaultValue={editing === "new" ? "" : editing.fromAccountId} required><option value="" disabled>Selecione</option>{accounts.filter((account) => account.isActive || editing !== "new" && account.id === editing.fromAccountId).map((account) => <option value={account.id} key={account.id}>{account.name} · {currency.format(account.balance)}{!account.isActive ? " (inativa)" : ""}</option>)}</select></label><label>Conta de destino<select name="toAccountId" defaultValue={editing === "new" ? "" : editing.toAccountId} required><option value="" disabled>Selecione</option>{accounts.filter((account) => account.isActive || editing !== "new" && account.id === editing.toAccountId).map((account) => <option value={account.id} key={account.id}>{account.name}{!account.isActive ? " (inativa)" : ""}</option>)}</select></label><label>Valor (R$)<input name="amount" type="number" min="0.01" step="0.01" defaultValue={editing === "new" ? "" : editing.amount} required /></label><label>Data<input name="date" type="date" defaultValue={editing === "new" ? today : editing.date.slice(0, 10)} required /></label><label>Status<select name="status" defaultValue={editing === "new" ? "COMPLETED" : editing.status}><option value="COMPLETED">Concluída</option><option value="PENDING">Agendada</option><option value="CANCELED">Cancelada</option></select></label></div><label>Observação<textarea name="notes" defaultValue={editing === "new" ? "" : editing.notes ?? ""} placeholder="Opcional" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Cancelar</button><button className="primary-button">Salvar transferência</button></div></form></section></div>}
  </section>;
}
