import { Router } from "express";
import { requireAdmin } from "../middleware/admin.js";
import { authenticate } from "../middleware/auth.js";
import { adminUsersRouter } from "./admin-users.js";
import { auditLogsRouter } from "./audit-logs.js";
import { accountsRouter } from "./accounts.js";
import { alertsRouter } from "./alerts.js";
import { authRouter } from "./auth.js";
import { categoriesRouter } from "./categories.js";
import { cardsRouter } from "./cards.js";
import { budgetsRouter } from "./budgets.js";
import { dashboardRouter } from "./dashboard.js";
import { reportsRouter } from "./reports.js";
import { forecastsRouter } from "./forecasts.js";
import { goalsRouter } from "./goals.js";
import { importsRouter } from "./imports.js";
import { recurrencesRouter } from "./recurrences.js";
import { transactionsRouter } from "./transactions.js";
import { transfersRouter } from "./transfers.js";

export const routes = Router();
routes.use("/auth", authRouter);
routes.use("/accounts", authenticate, accountsRouter);
routes.use("/alerts", authenticate, alertsRouter);
routes.use("/cards", authenticate, cardsRouter);
routes.use("/budgets", authenticate, budgetsRouter);
routes.use("/categories", authenticate, categoriesRouter);
routes.use("/transactions", authenticate, transactionsRouter);
routes.use("/transfers", authenticate, transfersRouter);
routes.use("/dashboard", authenticate, dashboardRouter);
routes.use("/reports", authenticate, reportsRouter);
routes.use("/forecasts", authenticate, forecastsRouter);
routes.use("/goals", authenticate, goalsRouter);
routes.use("/imports", authenticate, importsRouter);
routes.use("/recurrences", authenticate, recurrencesRouter);
routes.use("/admin/users", authenticate, requireAdmin, adminUsersRouter);
routes.use("/admin/audit-logs", authenticate, requireAdmin, auditLogsRouter);
